import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import LayoutSlice from "@/components/layout/LayoutSlice";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Promgrad Stroy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <LayoutSlice>{children}</LayoutSlice>
      </body>
    </html>
  );
}
